import { ExerciseConfig, ExerciseType } from '../types/exercise';
import { WorkoutSession, WorkoutSummaryStats } from '../types/workout';
import { Achievement, MonthlyStats, PersonalBest, UserProfile } from '../types/analytics';

export const EXERCISE_CONFIGS: Record<string, ExerciseConfig> = {
  pushups: {
    id: 'pushups',
    name: 'Push-ups',
    category: 'Upper Body',
    difficulty: 'Intermediate',
    description: 'The definitive upper-body compound movement building chest, triceps, anterior deltoids, and core stability.',
    detailedBio: 'GymBuddy tracks both elbow flexion depth and spinal alignment in real-time, verifying that your chest reaches target depth before ascending to a full lockout.',
    targetMuscles: ['Pectoralis Major', 'Triceps Brachii', 'Anterior Deltoids', 'Core & Serratus'],
    caloriesPerRep: 0.32,
    estimatedSecsPerRep: 2.2,
    iconName: 'Activity',
    cameraSetupAdvice: 'Position your device on the floor or a low stand 6-8 ft away, showing your full side profile from head to feet.',
    idealAngle: 'Side view (90° perpendicular)',
    keyLandmarks: ['Shoulder', 'Elbow', 'Wrist', 'Hip', 'Ankle'],
    color: {
      primary: '#00F5A0',
      border: 'border-emerald-500/30',
      bgGlow: 'from-emerald-500/20 to-teal-500/5',
    },
    instructions: [
      {
        step: 1,
        title: 'Side Profile Setup',
        instruction: 'Lie perpendicular to the camera so your shoulder, hip, and ankles are fully visible.',
        tip: 'Ensure proper lighting so your body contours are sharp.',
      },
      {
        step: 2,
        title: 'Plank Foundation',
        instruction: 'Set hands slightly wider than shoulder-width, glutes squeezed, forming a straight line from neck to heels.',
      },
      {
        step: 3,
        title: 'Controlled Descent',
        instruction: 'Lower your chest smoothly until elbows bend past 90 degrees.',
        tip: 'Avoid flaring elbows wide outward; keep them at a 45-degree arrow shape.',
      },
      {
        step: 4,
        title: 'Full Extension Ascent',
        instruction: 'Drive through your palms back to starting position with locked arms for a validated rep.',
      },
    ],
    formTips: [
      'Keep core braced to prevent hip sagging or piking',
      'Neutral neck position looking 6 inches ahead of fingers',
      'Achieve 90° or deeper at elbow vertex for valid rep registration',
    ],
    commonMistakes: [
      'Half repetitions without reaching 90° elbow bend',
      'Flaring elbows 90° straight sideways putting stress on shoulders',
      'Dipping hips to cheat range of motion',
    ],
  },
  situps: {
    id: 'situps',
    name: 'Sit-ups',
    category: 'Core',
    difficulty: 'Beginner',
    description: 'Foundational abdominal flexion strengthening the rectus abdominis, hip flexors, and deep stabilizer network.',
    detailedBio: 'GymBuddy tracks torso inclination against knee vertex angle, validating that the shoulder line passes the pelvic plane before lowering with control.',
    targetMuscles: ['Rectus Abdominis', 'Transverse Abdominis', 'Iliopsoas', 'Obliques'],
    caloriesPerRep: 0.25,
    estimatedSecsPerRep: 2.5,
    iconName: 'Zap',
    cameraSetupAdvice: 'Place device 6-8 ft away at eye/hip level, capturing full side profile including feet planted on the mat.',
    idealAngle: 'Side view (90° perpendicular)',
    keyLandmarks: ['Shoulder', 'Hip', 'Knee', 'Ankle'],
    color: {
      primary: '#00D9F5',
      border: 'border-cyan-500/30',
      bgGlow: 'from-cyan-500/20 to-blue-500/5',
    },
    instructions: [
      {
        step: 1,
        title: 'Side Mat Position',
        instruction: 'Lie on your back with knees bent at approximately 90 degrees and feet flat on the floor.',
      },
      {
        step: 2,
        title: 'Arm Placement',
        instruction: 'Cross hands across your chest or hold lightly beside ears (do not yank your neck).',
      },
      {
        step: 3,
        title: 'Abdominal Contraction',
        instruction: 'Curl your torso up toward your thighs until your chest is near upright (approx 70-80° angle).',
        tip: 'Focus on flexing abdominals rather than pulling with hip flexors alone.',
      },
      {
        step: 4,
        title: 'Controlled Reset',
        instruction: 'Lower back down with control until your shoulder blades touch the mat before starting next rep.',
      },
    ],
    formTips: [
      'Keep feet anchored flat throughout the movement',
      'Exhale on ascension, inhale on controlled descent',
      'Avoid pulling on head or neck with fingers',
    ],
    commonMistakes: [
      'Bouncing lower back off the floor without abdominal tension',
      'Yanking neck forward with hands behind head',
      'Lifting heels significantly off the floor',
    ],
  },
};

export const MOCK_PERSONAL_BESTS: Partial<Record<ExerciseType, PersonalBest>> = {
  pushups: {
    exerciseId: 'pushups',
    exerciseName: 'Push-ups',
    maxReps: 42,
    bestSessionDuration: 180,
    bestFormScore: 94,
    achievedAt: '2026-08-18T10:30:00Z',
  },
  situps: {
    exerciseId: 'situps',
    exerciseName: 'Sit-ups',
    maxReps: 55,
    bestSessionDuration: 210,
    bestFormScore: 96,
    achievedAt: '2026-08-20T17:15:00Z',
  },
};

export const MOCK_RECENT_WORKOUTS: WorkoutSession[] = [
  {
    id: 'wk-101',
    exerciseId: 'pushups',
    exerciseName: 'Push-ups',
    startTime: Date.now() - 1000 * 60 * 60 * 4, // 4 hours ago
    endTime: Date.now() - 1000 * 60 * 60 * 4 + 1000 * 185,
    durationSeconds: 185,
    totalReps: 35,
    validReps: 33,
    invalidReps: 2,
    averageFormScore: 92,
    caloriesBurned: 11.2,
    personalBestBeaten: false,
    streakContribution: true,
    repsHistory: [],
    feedbacks: [
      { id: 'f1', type: 'good', message: 'Consistent depth on reps 1-25', timestamp: 10000 },
      { id: 'f2', type: 'warning', message: 'Slight hip sag on rep 31', timestamp: 150000 },
    ],
  },
  {
    id: 'wk-102',
    exerciseId: 'situps',
    exerciseName: 'Sit-ups',
    startTime: Date.now() - 1000 * 60 * 60 * 26, // Yesterday
    endTime: Date.now() - 1000 * 60 * 60 * 26 + 1000 * 210,
    durationSeconds: 210,
    totalReps: 50,
    validReps: 48,
    invalidReps: 2,
    averageFormScore: 94,
    caloriesBurned: 12.5,
    personalBestBeaten: false,
    streakContribution: true,
    repsHistory: [],
    feedbacks: [
      { id: 'f3', type: 'good', message: 'Excellent torso verticality on ascend', timestamp: 30000 },
    ],
  },
  {
    id: 'wk-103',
    exerciseId: 'pushups',
    exerciseName: 'Push-ups',
    startTime: Date.now() - 1000 * 60 * 60 * 50, // 2 days ago
    endTime: Date.now() - 1000 * 60 * 60 * 50 + 1000 * 220,
    durationSeconds: 220,
    totalReps: 42,
    validReps: 42,
    invalidReps: 0,
    averageFormScore: 95,
    caloriesBurned: 13.4,
    personalBestBeaten: true,
    streakContribution: true,
    repsHistory: [],
    feedbacks: [
      { id: 'f4', type: 'good', message: 'Clean lockout across all sets', timestamp: 45000 },
    ],
  },
  {
    id: 'wk-104',
    exerciseId: 'situps',
    exerciseName: 'Sit-ups',
    startTime: Date.now() - 1000 * 60 * 60 * 74, // 3 days ago
    endTime: Date.now() - 1000 * 60 * 60 * 74 + 1000 * 190,
    durationSeconds: 190,
    totalReps: 45,
    validReps: 43,
    invalidReps: 2,
    averageFormScore: 89,
    caloriesBurned: 11.0,
    personalBestBeaten: false,
    streakContribution: true,
    repsHistory: [],
    feedbacks: [],
  },
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-rep',
    title: 'First Ignition',
    description: 'Complete your first AI-validated repetition with GymBuddy.',
    icon: 'Flame',
    tier: 'bronze',
    category: 'reps',
    progress: 100,
    unlocked: true,
    unlockedAt: '2026-08-10T09:00:00Z',
    requirementText: '1 Valid Rep',
  },
  {
    id: 'ach-streak-7',
    title: 'Relentless Momentum',
    description: 'Maintain an active daily workout streak for 7 consecutive days.',
    icon: 'Zap',
    tier: 'silver',
    category: 'streak',
    progress: 100,
    unlocked: true,
    unlockedAt: '2026-08-22T20:00:00Z',
    requirementText: '7-Day Streak',
  },
  {
    id: 'ach-century-club',
    title: 'Century Club',
    description: 'Accumulate 100 total verified push-ups or sit-ups in a single session.',
    icon: 'Trophy',
    tier: 'gold',
    category: 'reps',
    progress: 55,
    unlocked: false,
    requirementText: '100 Reps / Session',
  },
  {
    id: 'ach-flawless-form',
    title: 'Surgical Precision',
    description: 'Achieve a 95%+ average form score in a workout with at least 30 reps.',
    icon: 'ShieldCheck',
    tier: 'gold',
    category: 'form',
    progress: 100,
    unlocked: true,
    unlockedAt: '2026-08-20T17:15:00Z',
    requirementText: '95% Form on 30+ Reps',
  },
  {
    id: 'ach-iron-will',
    title: 'Iron Will',
    description: 'Reach a total cumulative lifetime count of 1,000 computer-vision verified reps.',
    icon: 'Crown',
    tier: 'platinum',
    category: 'volume',
    progress: 68,
    unlocked: false,
    requirementText: '1,000 Total Reps',
  },
  {
    id: 'ach-streak-30',
    title: 'Legendary Discipline',
    description: 'Maintain an uninterrupted 30-day streak of daily AI training.',
    icon: 'Sparkles',
    tier: 'diamond',
    category: 'streak',
    progress: 23,
    unlocked: false,
    requirementText: '30-Day Streak',
  },
];

export const MOCK_MONTHLY_STATS: MonthlyStats = {
  month: 'August 2026',
  totalReps: 684,
  totalWorkouts: 21,
  totalDurationMin: 94,
  totalCalories: 218,
  averageFormScore: 93,
  byExercise: {
    pushups: 392,
    situps: 292,
    squats: 0,
    pullups: 0,
  },
  dailyBreakdown: [
    { date: '2026-08-01', count: 30, calories: 9.6, durationMinutes: 4, hasWorkout: true },
    { date: '2026-08-02', count: 25, calories: 8.0, durationMinutes: 3, hasWorkout: true },
    { date: '2026-08-03', count: 0, calories: 0, durationMinutes: 0, hasWorkout: false },
    { date: '2026-08-04', count: 35, calories: 11.2, durationMinutes: 5, hasWorkout: true },
    { date: '2026-08-05', count: 40, calories: 12.8, durationMinutes: 6, hasWorkout: true },
    { date: '2026-08-06', count: 30, calories: 9.6, durationMinutes: 4, hasWorkout: true },
    { date: '2026-08-07', count: 0, calories: 0, durationMinutes: 0, hasWorkout: false },
    { date: '2026-08-08', count: 45, calories: 14.4, durationMinutes: 6, hasWorkout: true },
    { date: '2026-08-09', count: 32, calories: 10.2, durationMinutes: 4, hasWorkout: true },
    { date: '2026-08-10', count: 28, calories: 8.9, durationMinutes: 4, hasWorkout: true },
    { date: '2026-08-11', count: 35, calories: 11.2, durationMinutes: 5, hasWorkout: true },
    { date: '2026-08-12', count: 0, calories: 0, durationMinutes: 0, hasWorkout: false },
    { date: '2026-08-13', count: 40, calories: 12.8, durationMinutes: 5, hasWorkout: true },
    { date: '2026-08-14', count: 35, calories: 11.2, durationMinutes: 5, hasWorkout: true },
    { date: '2026-08-15', count: 30, calories: 9.6, durationMinutes: 4, hasWorkout: true },
    { date: '2026-08-16', count: 42, calories: 13.4, durationMinutes: 6, hasWorkout: true },
    { date: '2026-08-17', count: 50, calories: 15.0, durationMinutes: 7, hasWorkout: true },
    { date: '2026-08-18', count: 42, calories: 13.4, durationMinutes: 6, hasWorkout: true },
    { date: '2026-08-19', count: 38, calories: 11.8, durationMinutes: 5, hasWorkout: true },
    { date: '2026-08-20', count: 55, calories: 17.6, durationMinutes: 7, hasWorkout: true },
    { date: '2026-08-21', count: 50, calories: 12.5, durationMinutes: 6, hasWorkout: true },
    { date: '2026-08-22', count: 45, calories: 11.0, durationMinutes: 5, hasWorkout: true },
    { date: '2026-08-23', count: 35, calories: 11.2, durationMinutes: 4, hasWorkout: true },
  ],
};

export const MOCK_SUMMARY_STATS: WorkoutSummaryStats = {
  totalWorkouts: 24,
  totalReps: 890,
  totalDurationMinutes: 128,
  totalCalories: 285,
  currentStreak: 7,
  longestStreak: 12,
  completionRate: 96,
  accuracyRate: 94.2,
};

export const MOCK_USER_PROFILE: UserProfile = {
  id: 'usr-athlete-01',
  name: 'Alex Vance',
  email: 'alex.vance@gymbuddy.ai',
  joinedDate: '2026-07-15',
  level: 8,
  xp: 3420,
  nextLevelXp: 5000,
  currentStreak: 7,
  longestStreak: 12,
  personalBests: MOCK_PERSONAL_BESTS as Record<ExerciseType, PersonalBest>,
  recentWorkouts: MOCK_RECENT_WORKOUTS,
  achievements: MOCK_ACHIEVEMENTS,
};
