-- ============================================================================
-- GYMBUDDY DATABASE SCHEMA MIGRATION
-- Tables: public.profiles, public.workout_sessions
-- ============================================================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1. TABLE: public.profiles
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  avatar_url TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Comments
COMMENT ON TABLE public.profiles IS 'Athlete user profiles linked 1:1 with Supabase Auth users';
COMMENT ON COLUMN public.profiles.id IS 'Primary key referencing auth.users.id';
COMMENT ON COLUMN public.profiles.name IS 'Athlete display name / full name';
COMMENT ON COLUMN public.profiles.email IS 'Athlete email address';

-- Trigger to update updated_at timestamp on profiles
CREATE OR REPLACE FUNCTION public.handle_profile_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_profiles_updated ON public.profiles;
CREATE TRIGGER on_profiles_updated
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_profile_updated_at();

-- Trigger to automatically create profile record on auth.users registration
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data->>'name',
      NEW.raw_user_meta_data->>'full_name',
      split_part(NEW.email, '@', 1),
      'Athlete'
    ),
    COALESCE(NEW.email, '')
  )
  ON CONFLICT (id) DO UPDATE
  SET
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- ============================================================================
-- 2. TABLE: public.workout_sessions
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.workout_sessions (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  exercise_id TEXT NOT NULL,
  exercise_name TEXT NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  duration_seconds INTEGER NOT NULL DEFAULT 0 CONSTRAINT duration_seconds_non_negative CHECK (duration_seconds >= 0),
  total_reps INTEGER NOT NULL DEFAULT 0 CONSTRAINT total_reps_non_negative CHECK (total_reps >= 0),
  valid_reps INTEGER NOT NULL DEFAULT 0 CONSTRAINT valid_reps_non_negative CHECK (valid_reps >= 0),
  invalid_reps INTEGER NOT NULL DEFAULT 0 CONSTRAINT invalid_reps_non_negative CHECK (invalid_reps >= 0),
  average_form_score INTEGER NOT NULL DEFAULT 0 CONSTRAINT average_form_score_range CHECK (average_form_score >= 0 AND average_form_score <= 100),
  personal_best_beaten BOOLEAN NOT NULL DEFAULT false,
  streak_contribution BOOLEAN NOT NULL DEFAULT true,
  reps_history JSONB NOT NULL DEFAULT '[]'::jsonb,
  feedbacks JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Comments
COMMENT ON TABLE public.workout_sessions IS 'Authoritative historical workout records generated by computer-vision workouts';
COMMENT ON COLUMN public.workout_sessions.id IS 'Unique workout session identifier (e.g., wk-1726442400000)';
COMMENT ON COLUMN public.workout_sessions.user_id IS 'Foreign key referencing auth.users.id of the athlete';
COMMENT ON COLUMN public.workout_sessions.reps_history IS 'Detailed per-rep telemetry array (repNumber, durationMs, formScore, timestamp, etc.)';
COMMENT ON COLUMN public.workout_sessions.feedbacks IS 'Real-time biomechanical feedback array captured during workout';

-- ============================================================================
-- 3. INDEXES
-- ============================================================================
-- High performance index for user timeline queries, monthly stats, and weekly volume
CREATE INDEX IF NOT EXISTS idx_workout_sessions_user_time 
  ON public.workout_sessions (user_id, start_time DESC);

-- Performance index for filtering personal bests and exercise breakdown
CREATE INDEX IF NOT EXISTS idx_workout_sessions_user_exercise 
  ON public.workout_sessions (user_id, exercise_id);

-- ============================================================================
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile"
  ON public.profiles
  FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile"
  ON public.profiles
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
  ON public.profiles
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Enable RLS on workout_sessions
ALTER TABLE public.workout_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own workout sessions" ON public.workout_sessions;
CREATE POLICY "Users can view own workout sessions"
  ON public.workout_sessions
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own workout sessions" ON public.workout_sessions;
CREATE POLICY "Users can insert own workout sessions"
  ON public.workout_sessions
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own workout sessions" ON public.workout_sessions;
CREATE POLICY "Users can update own workout sessions"
  ON public.workout_sessions
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own workout sessions" ON public.workout_sessions;
CREATE POLICY "Users can delete own workout sessions"
  ON public.workout_sessions
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);
